requires:
  - https://github.com/moremoban/pypi-mobans
configuration:
  template_dir:
    - "usercache://moban:chfw/repos/pypi-mobans/templates"
    - local
  configuration: config.yml
  configuration_dir: "usercache://moban:chfw/repos/pypi-mobans/config"
targets:
  - mytravis.yml: travis.yml.jj2
  - test.txt: demo.txt.jj2
